<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="DirectShowLib.Standard" Version="2.1.0" />
		<PackageReference Include="log4net" Version="3.0.3" />
		<PackageReference Include="OpenCvSharp4" Version="4.8.0.20230708" />
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.8.0.20230708" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.8.0.20230708" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="2.5.1" />
		<PackageReference Include="Sdcb.PaddleOCR" Version="2.7.0" />
		<PackageReference Include="Sdcb.PaddleOCR.Models.Local" Version="2.7.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
		<PackageReference Include="ViewFaceCore" Version="0.3.8" />
		<PackageReference Include="ViewFaceCore.Extension.SkiaSharp" Version="0.3.7" />
		<PackageReference Include="ViewFaceCore.model.face_detector" Version="6.0.7" />
		<PackageReference Include="ViewFaceCore.model.face_landmarker_pts5" Version="6.0.7" />
		<PackageReference Include="ViewFaceCore.model.face_recognizer" Version="6.0.7" />
		<PackageReference Include="ViewFaceCore.model.fas_first" Version="6.0.7" />
		<PackageReference Include="ViewFaceCore.model.fas_second" Version="6.0.7" />
		<PackageReference Include="ViewFaceCore.runtime.win.vc" Version="6.0.0" />
		<PackageReference Include="ViewFaceCore.runtime.win.x64" Version="6.0.7" />
		<PackageReference Include="ViewFaceCore.runtime.win.x86" Version="6.0.7" />
		<PackageReference Include="ZXing.Net" Version="0.16.10" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
		<PackageReference Include="ZXing.Net.Bindings.ImageSharp" Version="0.16.15" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="AForge.Video.DirectShow">
	    <HintPath>AForge.Video.DirectShow.dll</HintPath>
	  </Reference>
	  <Reference Include="LibUsbDotNetF">
	    <HintPath>LibUsbDotNetF.dll</HintPath>
	  </Reference>
	  <Reference Include="NextBiometrics.Biometrics">
	    <HintPath>NextBiometrics.Biometrics.dll</HintPath>
	  </Reference>
	  <Reference Include="RAR.IdCard.Crypt">
	    <HintPath>RAR.IdCard.Crypt.dll</HintPath>
	  </Reference>
	  <Reference Include="RAR.IdCard.Models">
	    <HintPath>RAR.IdCard.Models.dll</HintPath>
	  </Reference>
	  <Reference Include="RAR.IdCard.Sdk.Entities">
	    <HintPath>RAR.IdCard.Sdk.Entities.dll</HintPath>
	  </Reference>
	  <Reference Include="RAR.IdCard.Sdk.Models">
	    <HintPath>RAR.IdCard.Sdk.Models.dll</HintPath>
	  </Reference>
	  <Reference Include="RAR.IdCard.Sdk.Reader">
	    <HintPath>RAR.IdCard.Sdk.Reader.dll</HintPath>
	  </Reference>
	  <Reference Include="RAR.IdCard.Sdk.Utils.TKCrypto">
	    <HintPath>RAR.IdCard.Sdk.Utils.TKCrypto.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
	  <None Update="hidapi.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="libusb-1.0.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="libzbar-0.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="NBBiometrics.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>